polls2/urls.py
from django.conf.urls import url

from views import index, add_task, task_list, del_task, edit_task, edit_without_refresh

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add_task, name='add_task'),
    url(r'^tasks/$', task_list, name='tasks'),
    url(r'^delete/(?P<pk>[0-9]+)/$', del_task, name='delete'),
    url(r'^edit/(?P<pk>[0-9]+)/$', edit_task, name='edit_task'),
    url(r'^edit_without_referesh/$', edit_without_refresh, name='edit_without_refresh'),
]

task/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'task.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^', include('polls2.urls', namespace="task_manager")),
    url(r'^admin/', include(admin.site.urls)),
)

polls2/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    pub_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField('due date')
    modification_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

    def delete_task(self):
        return reverse('task_manager:delete', args=(self.pk,))

    @property
    def task_edit(self):
    	return reverse('task_manager:edit_task', args=(self.pk,))

polls2/forms.py
from django import forms
from django.conf import settings
from .models import Task
from django.contrib.admin import widgets  



class FormTaskAdd(forms.ModelForm):
    name = forms.CharField(max_length=40, required=False)
    description = forms.CharField(widget=forms.Textarea, max_length=200, required=False)
    due_date = forms.DateField(required=False, input_formats=settings.DATE_INPUT_FORMATS )

    class Meta:
    	model = Task
    	fields = ('name', 'description', 'due_date')

  #   def clean_name(self):
		# name = self.cleaned_data.get('name')
		# if name is not None and not name :
		# 	self.add_error(
		# 		'name',
		# 		'Cant be empty'
		# 	)
		# return name
class FormName(forms.ModelForm):
	name = forms.CharField(max_length=40, required=False)

	class Meta:
		model = Task
		fields = ('name',)

	def clean_name(self):
		name = self.cleaned_data.get('name')
		if name is not None and not name :
			self.add_error(
				'name',
				'Cant be empty'
			)
		return name

class FormDescription(forms.ModelForm):
	description = forms.CharField(widget=forms.Textarea, max_length=200, required=False)

	class Meta:
		model = Task
		fields = ('description',)

	def clean_description(self):
		description = self.cleaned_data.get('description')
		if description is not None and not description :
			self.add_error(
				'description',
				'Cant be empty'
			)
		return description

class FormDueDate(forms.ModelForm):
	due_date = forms.DateField(required=True, input_formats=settings.DATE_INPUT_FORMATS )

	class Meta:
		model = Task
		fields = ('due_date',)

	def clean_due_date(self):
		due_date = self.cleaned_data.get('due_date')
		if due_date is not None and not due_date :
			self.add_error(
				'due_date',
				'Cant be empty'
			)
		return due_date
# widget=forms.widgets.DateInput(format="%m/%d/%Y")

polls2/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .models import Task
from .forms import FormTaskAdd, FormName, FormDescription, FormDueDate

def index(request):
    return render(request, 'polls2/index.html')

def add_task(request):
    tasks = Task.objects.all()
    if request.method == 'POST':
        form = FormTaskAdd(request.POST)
        if form.is_valid():
            # task = form.save(commit=False)
            form.save()
            return render(request, 'polls2/task_list.html', {'task_list':tasks})
    else:        
        form = FormTaskAdd()
    return render(request, 'polls2/add_task.html', {'form':form})

def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'polls2/task_list.html', {'task_list':tasks})

def del_task(request, pk):
    tasks = get_object_or_404(Task, pk = pk)
    tasks.delete()
    return HttpResponseRedirect("/tasks/")

def edit_task(request, pk):
    tasks = Task.objects.all()
    task = Task.objects.get(pk=pk)
    if request.POST:
        form=FormTaskAdd(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return render(request, 'polls2/task_list.html', {'task_list':tasks})
    else:
        form=FormTaskAdd(instance=task)
    return render(request, 'polls2/task_edit.html', {'form':form, 'task': task})

def edit_without_refresh(request):
    if request.POST:
        task = get_object_or_404(Task, pk = request.POST.get('pk'))
        field_name = request.POST.get('name')
        field_value = request.POST.get('value')
        data = {field_name: field_value }
        form=FormTaskAdd( data  ,instance=task)
        #1 form_name = FormName(data, instance=task)
        #1 form_description = FormDescription(data, instance=task)
        #1 form_duedate = FormDueDate(data, instance=task)
        #1 if field_name == 'name' or field_name =='description' or field_name == 'due_date':
        if form.is_valid() and field_value !='':
            form.save()
            return JsonResponse({'success': ' Yesss! '}) 
        else:
            errors = dict((k, map(unicode, v))for (k,v) in form.errors.items())
            print errors
            errors.update({'error': ' Nooo! '})
            errors 
            return JsonResponse(errors)
    else:
        form=FormTaskAdd(instance=task)
    return HttpResponse()




    #1         if form_name.is_valid():
    #             form.save()
    #             return JsonResponse({
    #                 'success': ' Yesss! '
    #             }) 
    #         else:
    #             errors = dict(
    #                 (k, map(unicode, v))
    #                 for (k,v) in form.errors.items()
    #             )
    #             print errors
    #             errors.update({'error': ' Nooo! '})
    #             errors 
    #             return JsonResponse(errors)
    #     elif field_name == 'description':
    #         if form_description.is_valid():
    #             form.save()
    #             return JsonResponse({
    #                 'success': ' Yesss! '
    #             }) 
    #         else:
    #             errors = dict(
    #                 (k, map(unicode, v))
    #                 for (k,v) in form.errors.items()
    #             )
    #             print errors
    #             errors.update({'error': ' Nooo! '})
    #             errors 
    #             return JsonResponse(errors)
    #     elif field_name == 'due_date':
    #         if form_duedate.is_valid():
    #             form.save()
    #             return JsonResponse({
    #                 'success': ' Yesss! '
    #             }) 
    #         else:
    #             errors = dict(
    #                 (k, map(unicode, v))
    #                 for (k,v) in form.errors.items()
    #             )
    #             print errors
    #             errors.update({'error': ' Nooo! '})
    #             errors 
    #             return JsonResponse(errors)
    # else:
    #     form=FormTaskAdd(instance=task)
    #1 return HttpResponse()

polls2/templates/index.html
{% load static %}
<html lang="en">
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap-editable.css' %}" rel="stylesheet">
  </head>

<body>

<nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'task_manager:tasks' %}">List of Tasks</a></li>
              <li><a href="{% url 'task_manager:add_task' %}">Add New Task</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/bootstrap-editable.js'%} "></script>
    <script src="{% static 'js/task_editable.js' %}"></script>

  </body>
</html>

polls2/templates/polls2/add_task.html
{% include "index.html" %}

{% block content %}

<form action="{% url 'task_manager:add_task' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

{% endblock content%}

polls2/templates/polls2/index.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-editable.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/table.css" rel="stylesheet">

  </head>

<body>

<nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'task_manager:tasks' %}">List of Tasks</a></li>
              <li><a href="{% url 'task_manager:add_task' %}">Add New Task</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      {% block content %}
      {% endblock%}
      
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-editable.js"></script>
    <script src="{{ STATIC_URL }}js/editable.js"></script>

  </body>
</html>

polls2/templates/polls2/task_edit.html
<html>
<head>
	<title></title>
</head>
<body>
<form action="{%url 'task_manager:edit_task' task.id %}" method="post">
	{%csrf_token%}
	{{form.as_p}}
<input type="submit" value="Submit" />
</form>
	
</body>
</html>

polls2/templates/polls2/task_list.html
{% include "index.html" %}

{% block content %}

<table border="5" style="width:70%">
    <tr>
        <th>Name</th>
        <th>Description</th> 
        <th>Due date</th>
    </tr>
    {% for task in task_list %}
    <tr>
        <td>
        <a href="" class="name" data-name="name" data-type="text" data-placement="right" data-pk="{{task.pk}}" data-url="{% url 'task_manager:edit_without_refresh' %}" data-title="name">{{ task.name }}</a>
        </td> 
        <td>
        <a href="" class="description" data-name="description" data-type="text" data-placement="right" data-pk="{{task.pk}}" data-url="{% url 'task_manager:edit_without_refresh' %}" data-title="description">{{ task.description }}</a>
        </td> 
        <td>
        <a href="" class="due_date" data-name="due_date" data-type="text" data-placement="right" data-pk="{{task.pk}}" data-url="{% url 'task_manager:edit_without_refresh' %}" data-title="due_date">{{ task.due_date }}</a>
        </td> 
        <td><a href="{{ task.delete_task }}">Delete</a></td>
        <td><a href="{{ task.task_edit }}">Edit</a></td>
    </tr>
    {% endfor %}
</table>
        <span class="success" ></span>
        <span class="error"></span>

{% endblock %}